import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { FaFacebookF, FaInstagram } from "react-icons/fa";
import { FaSquareYoutube, FaXTwitter } from "react-icons/fa6";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}

const Footer = () => {
  const size = 24;
  return (
    <footer>
      <div className="social-links">
        <a href="#" aria-label="Facebook page">
          <FaFacebookF size={size} />
        </a>
        <a href="#">
          <FaInstagram size={size} aria-label="Instagram page" />
        </a>
        <a href="#">
          <FaSquareYoutube size={size} aria-label="Linkedin page" />
        </a>
        <a href="#">
          <FaXTwitter size={size} aria-label="X page" />
        </a>
      </div>

      <span className="copy-right">&copy;2024 Ottawa, ON.</span>
    </footer>
  );
};
